---
title: "MIDTERM EXAM"
author: "Cecilia Nartey"
date: "10/15/2022"
output: html_document
---

```{r}
# library packages

library(readr)
library(haven)
pacman::p_load(haven, readr, dplyr, openxlsx)
```

```{r}
# import dataset from github
 titanic <- read_csv("https://github.com/kijohnson/Data/blob/main/titanic.csv?raw=true")
```

```{r}
# Determine median age by passenger class
titanic %>%
    group_by(Pclass) %>%
    dplyr::summarize(median_age = median(Age, na.rm=TRUE))

```
# The median age of passengers in first class was 38.5 years
# The median age of passengers in second class was 29 years
# The median age of passengers in third class was 24 years

```{r}
library('tidyverse')
```

```{r}
# plot of medians by passenger class

ggplot(data = titanic) +
  stat_summary(
    mapping = aes(x= Pclass, y = Age),
    fun.min = min,
    fun.max = max,
    fun = median
  )
```

```{r}
# spread of data and outliers for age by passenger class
ggplot(data = titanic)+
  geom_point(aes(x= Pclass, y= Age)) + 
  stat_summary(mapping = aes(x = Pclass, y = Age),
    fun = median, geom = "crossbar", width = 0.4)

```
```{r}
# percentage of males and females by class

# first, install and library table1
install.packages(table1)
library(table1)

# check sex class
class("Sex")

# change sex to factor
titanic$Sex <- as.factor(titanic$Sex)
class(titanic$Sex)


# Now, percentage of males and females by class
table1(~Sex | Pclass, data= titanic)
 
```


```{r}
# plot that shows medians, spread of data, and outliers for the continuous variable age according to passenger class
ttp = ggplot(titanic, aes(x = factor(Pclass), y = Age, fill = factor(Pclass))) +
  geom_boxplot() +
  stat_summary(
    aes(label = round(stat(y), 1)),
    geom = "text",
    fun = function(y) { o <- boxplot.stats(y)$out; if(length(o) == 0) NA else o },
    hjust = -1, size = 2
  )


ttp



```

